{
 "title": "pfSense System Dashboard -Flux",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dataSource", "query": "influxdb" },
   { "name": "bucket", "query": "buckets() " },
   {
    "name": "Host",
    "label": "pfSense",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: \"pfsense\", tag:\"host\")"
   },
   {
    "name": "Disk",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(\r\n  bucket: \"pfsense\",\r\n  tag: \"device\",\r\n  predicate: (r) => r[\"_measurement\"] == \"disk\" and r[\"host\"] =~ /^$Host$/,\r\n  start: -30d\r\n)\r\n"
   },
   {
    "name": "Gateway",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(\r\n  bucket: \"pfsense\",\r\n  tag: \"gateway_name\",\r\n  predicate: (r) => r[\"_measurement\"] == \"gateways\" and r[\"host\"] =~ /${Host}$/,\r\n  start: -30d\r\n)\r\n"
   },
   { "name": "WAN", "query": "igb0,ovpnc1" },
   {
    "name": "LAN_Interfaces",
    "label": "LAN",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(\r\n  bucket: \"pfsense\",\r\n  tag: \"interface\",\r\n  predicate: (r) => r[\"_measurement\"] == \"net\" and r[\"host\"] =~ /${Host}$/,\r\n  start: -30d\r\n)\r\n"
   },
   {
    "name": "CPU",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(\r\n  bucket: \"pfsense\",\r\n  tag: \"cpu\",\r\n  predicate: (r) => r[\"_measurement\"] == \"cpu\" and r[\"host\"] =~ /^${Host}$/,\r\n  start: -30d\r\n)\r\n|> filter(fn: (r) => r._value != \"cpu-total\")\r\n"
   },
   {
    "name": "Sensor",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(\r\n  bucket: \"pfsense\",\r\n  tag: \"sensor\",\r\n  predicate: (r) => r[\"_measurement\"] == \"temperature\" and r[\"host\"] =~ /^${Host}$/,\r\n  start: -30d\r\n)\r\n"
   }
  ]
 },
 "panels": [
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "system",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"n_users\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"$Host\")\r\n  |> rename(columns:{_value: \"n_users\"})\r\n  |> keep(columns:[\"n_users\"])\r\n  |> last(column: \"n_users\") ",
     "select": [
      [
       { "params": [ "n_users" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "CPU Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_idle\")\r\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\r\n  |> filter(fn: (r) => r[\"host\"] ==  \"$Host\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value * -1.0 + 100.0 }))\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_cpu",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_system\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${Host:pipe}$/)\r\n  |> filter(fn: (r) => r[\"cpu\"] =~ /^${CPU:pipe}$/)\r\n  //this aggregatewindow function will unfortunately artificially reduce the max value shown on the chart\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns:[\"_time\",\"cpu\",\"_value\"])\r\n\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "cpu", "operator": "=~", "value": "/^$CPU$/" }
     ]
    }
   ]
  },
  {
   "title": "PF Information",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "measurement": "pf",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pf\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"match\" or r[\"_field\"] == \"state-mismatch\" or r[\"_field\"] == \"state-insert\")\r\n  |> filter(fn: (r) => r[\"host\"] ==  \"$Host\" )\r\n  |> drop(columns:[\"host\",\"_measurement\",\"_start\",\"_stop\"])\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> rename(columns:{match:\"Match\",\"state-insert\":\"State Insert\",\"state-mismatch\":\"State Mismatch\"})  \r\n  |> last(column: \"_time\")\r\n",
     "select": [
      [
       { "params": [ "match" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Match" ], "type": "alias" }
      ],
      [
       { "params": [ "state-mismatch" ], "type": "field" },
       { "params": [ "State Mismatch" ], "type": "alias" }
      ],
      [
       { "params": [ "state-insert" ], "type": "field" },
       { "params": [ "State Insert" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"load1\" or r[\"_field\"] == \"load5\" or r[\"_field\"] == \"load15\")\r\n  |> filter(fn: (r) => r[\"host\"] ==  \"$Host\" )  \r\n  |> drop(columns:[\"host\",\"_measurement\",\"_start\",\"_stop\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\"_time\",\"load1\",\"load5\",\"load15\"])\r\n\r\n  \r\n",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load1" ], "type": "alias" }
      ],
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load5" ], "type": "alias" }
      ],
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load15" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Load 15m",
     "measurement": "system",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime_format\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"$Host\")\r\n  |> rename(columns:{_value: \"uptime_format\"})\r\n  |> keep(columns:[\"uptime_format\"])\r\n  |> last(column: \"uptime_format\") ",
     "select": [
      [
       { "params": [ "uptime_format" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Process Information",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "measurement": "processes",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"processes\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"idle\" or r[\"_field\"] == \"sleeping\" or r[\"_field\"] == \"wait\" or r[\"_field\"] == \"blocked\" or r[\"_field\"] == \"running\" or r[\"_field\"] == \"stopped\" or r[\"_field\"] == \"total\" or r[\"_field\"] == \"zombies\")\r\n  |> filter(fn: (r) => r[\"host\"] ==  \"$Host\" )\r\n  |> drop(columns:[\"host\",\"_measurement\",\"_start\",\"_stop\"])\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> last(column: \"_time\")\r\n",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Running" ], "type": "alias" }
      ],
      [
       { "params": [ "idle" ], "type": "field" }
      ],
      [
       { "params": [ "sleeping" ], "type": "field" }
      ],
      [
       { "params": [ "wait" ], "type": "field" }
      ],
      [
       { "params": [ "blocked" ], "type": "field" }
      ],
      [
       { "params": [ "zombies" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_path",
     "groupBy": [
      { "params": [ "path" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> filter(fn: (r) => r[\"device\"] != \"devfs\" and r[\"device\"] =~ /^${Disk:regex}$/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"path\"])\r\n  |> keep(columns: [\"_time\",\"path\",\"used_percent\"])\r\n  |> rename(columns: {\"used_percent\":\"_value\"})\r\n",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "device", "operator": "!=", "value": "devfs" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$Disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Ram",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${Host:pipe}$/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns:[\"_time\",\"_value\"])\r\n  |> rename(columns: {_value:\"Ram Used\"})\r\n\r\n",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Ram Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swap",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"swap\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${Host:pipe}$/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns:[\"_time\",\"_value\"])\r\n  |> rename(columns: {_value:\"Swap Used\"})\r\n\r\n",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "SWAP Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature Sensors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"degrees\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${Host:pipe}$/)\r\n  |> filter(fn: (r) => r[\"sensor\"] =~ /^${Sensor:regex}$/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns:[\"_time\",\"sensor\",\"_value\"])\r\n",
     "select": [
      [
       { "params": [ "degrees" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "sensor", "operator": "=~", "value": "/^$Sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "pfBlocker Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "IP - Top 10 Blocked - IN",
     "type": "table",
     "gridPos": { "h": 9, "w": 3, "x": 0, "y": 14 },
     "targets": [
      {
       "alias": "$tag_src_ip",
       "groupBy": [
        { "params": [ "src_ip" ], "type": "tag" }
       ],
       "measurement": "tail_ipblock",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\")\r\n\r\n  |> filter(fn: (r) => r[\"_field\"] == \"src_ip\" or r[\"_field\"] == \"dest_ip\" or r[\"_field\"] == \"dest_port\" or r[\"_field\"] == \"action\" or r[\"_field\"] == \"direction\" or r[\"_field\"] == \"protocolid\" or r[\"_field\"] == \"host\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.host =~ /^.*$/ and r.action == \"block\" and r.direction == \"in\" and r.protocolid =~ /^(6$|17$)/)\r\n  |> group(columns:[\"src_ip\"])\r\n  |> rename(columns:{action: \"Blocked\"})\r\n  |> count(column: \"Blocked\")\r\n  \r\n  |> group()  //use group to ungroup data and return to a single table\r\n  |> top(n:10, columns: [\"Blocked\"])  \r\n  |> sort(columns: [\"Blocked\"], desc: true)\r\n  |> yield()",
       "select": [
        [
         { "params": [ "action" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "action", "operator": "=", "value": "block" },
        { "condition": "AND", "key": "direction", "operator": "=", "value": "in" }
       ]
      }
     ]
    },
    {
     "title": "IP - Top 10 Blocked - OUT",
     "type": "table",
     "gridPos": { "h": 9, "w": 3, "x": 3, "y": 14 },
     "targets": [
      {
       "alias": "$tag_src_ip",
       "groupBy": [
        { "params": [ "src_ip" ], "type": "tag" }
       ],
       "measurement": "tail_ipblock",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\")\r\n\r\n  |> filter(fn: (r) => r[\"_field\"] == \"src_ip\" or r[\"_field\"] == \"dest_ip\" or r[\"_field\"] == \"dest_port\" or r[\"_field\"] == \"action\" or r[\"_field\"] == \"direction\" or r[\"_field\"] == \"protocolid\" or r[\"_field\"] == \"host\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.host =~ /^.*$/ and r.action == \"block\" and r.direction == \"out\" and r.protocolid =~ /^(6$|17$)/)\r\n  |> group(columns:[\"src_ip\",\"dest_ip\"])\r\n  |> rename(columns:{action: \"Blocked\"})\r\n  |> count(column: \"Blocked\")\r\n  \r\n  |> group()  //use group to ungroup data and return to a single table\r\n  |> top(n:10, columns: [\"Blocked\"])  \r\n  |> sort(columns: [\"Blocked\"], desc: true)\r\n  |> yield()",
       "select": [
        [
         { "params": [ "action" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "action", "operator": "=", "value": "block" },
        { "condition": "AND", "key": "direction", "operator": "=", "value": "in" }
       ]
      }
     ]
    },
    {
     "title": "IP - Blocked Packet Stats",
     "type": "stat",
     "gridPos": { "h": 9, "w": 3, "x": 6, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "tail_ip_block_log",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\")\r\n\r\n  |> filter(fn: (r) => r[\"_field\"] == \"action\" or r[\"_field\"] == \"direction\" or r[\"_field\"] == \"host\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.host =~ /^.*$/ and r.action == \"block\")\r\n  |> group(columns:[\"direction\"])\r\n  |> rename(columns:{action: \"Blocked\"})\r\n  |> count(column: \"Blocked\")",
       "select": [
        [
         { "params": [ "action" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         },
         { "params": [ "Blocked Inbound" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "direction", "operator": "=", "value": "in" },
        { "condition": "AND", "key": "action", "operator": "=", "value": "block" }
       ]
      }
     ]
    },
    {
     "title": "IP - Src/Dst Blocked Geo",
     "type": "grafana-worldmap-panel",
     "gridPos": { "h": 9, "w": 6, "x": 9, "y": 14 },
     "valueName": "total",
     "targets": [
      {
       "alias": "$tag_geoip_code",
       "groupBy": [
        { "params": [ "10m" ], "type": "time" },
        { "params": [ "geoip_code" ], "type": "tag" }
       ],
       "measurement": "tail_ip_block_log",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\" )\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${Host}$/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r[\"direction\"] == \"in\" and r[\"action\"] == \"block\")\r\n  |> keep(columns: [\"_time\",\"geoip_code\"])\r\n  //give each row a 1 value so that we can use count during the row aggregation\r\n  |> map(fn: (r) => ({ r with _value: 1 }))\r\n  |> group(columns: [\"geoip_code\"])  \r\n  |> window(every: 10m)\r\n  |> count()\r\n  |> duplicate(column: \"_stop\", as: \"_time\")\r\n  |> keep(columns: [\"_time\",\"geoip_code\",\"_value\"])\r\n  \r\n\r\n  ",
       "select": [
        [
         { "params": [ "action" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "action", "operator": "=", "value": "block" },
        { "condition": "AND", "key": "direction", "operator": "=", "value": "in" }
       ]
      }
     ]
    },
    {
     "title": "DNSBL - Blocked Domain Queries",
     "type": "stat",
     "gridPos": { "h": 9, "w": 3, "x": 15, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "tail_dnsbl_log",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_dnsbl_log\")\r\n//host is still a tag atm\r\n  |> filter(fn: (r) => r.host =~ /^.*$/)\r\n \r\n|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n|> group()\r\n|> rename(columns:{duplicateeventstatus:\"Blocked Domain Queries\"})\r\n|> count(column:\"Blocked Domain Queries\")\r\n\r\n",
       "select": [
        [
         { "params": [ "duplicateeventstatus" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         },
         { "params": [ "Blocked Domain Queries" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    },
    {
     "title": "DNSBL- Source IP - Top 10 Blocked",
     "type": "table",
     "gridPos": { "h": 9, "w": 3, "x": 18, "y": 14 },
     "targets": [
      {
       "alias": "$tag_src_ip",
       "groupBy": [
        { "params": [ "tld" ], "type": "tag" }
       ],
       "measurement": "tail_dnsbl",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_dnsbl_log\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  //src_ip is currently a tag\r\n  |> group(columns: [\"src_ip\"])\r\n|> filter(fn: (r) => r.host =~ /^.*$/)\r\n  |> keep(columns: [\"_time\",\"host\",\"src_ip\",\"domain\"])\r\n  //counting any column that isnt src_ip\r\n  |> count(column:\"domain\")  \r\n  |> rename(columns:{domain:\"Blocked\"})\r\n  |> group()  //use group to ungroup data and return to a single table\r\n  |> top(n:10, columns: [\"Blocked\"])  \r\n  |> sort(columns: [\"Blocked\"], desc: true)\r\n  |> yield()",
       "select": [
        [
         { "params": [ "domain" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    },
    {
     "title": "DNSBL - Top 10 Blocked Domains",
     "type": "table",
     "gridPos": { "h": 9, "w": 3, "x": 21, "y": 14 },
     "targets": [
      {
       "alias": "$tag_src_ip",
       "groupBy": [
        { "params": [ "tld" ], "type": "tag" }
       ],
       "measurement": "tail_dnsbl",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_dnsbl_log\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  //tld is currently a tag\r\n  |> group(columns: [\"tld\"])\r\n|> filter(fn: (r) => r.host =~ /^.*$/)\r\n  |> keep(columns: [\"_time\",\"host\",\"tld\",\"domain\"])\r\n  //counting any column that isnt tld\r\n  |> count(column:\"domain\")  \r\n  |> rename(columns:{domain:\"Blocked\"})\r\n  |> group()  //use group to ungroup data and return to a single table\r\n  |> top(n:10, columns: [\"Blocked\"])  \r\n  |> sort(columns: [\"Blocked\"], desc: true)\r\n  |> yield()",
       "select": [
        [
         { "params": [ "domain" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "pfBlocker Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "IP - Top 10 Blocked - IN (By Host/Port)",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 15 },
     "targets": [
      {
       "alias": "$tag_src_ip",
       "groupBy": [
        { "params": [ "src_ip" ], "type": "tag" }
       ],
       "measurement": "tail_ipblock",
       "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\")\n\n  |> filter(fn: (r) => r[\"_field\"] == \"src_ip\" or r[\"_field\"] == \"dest_ip\" or r[\"_field\"] == \"dest_port\" or r[\"_field\"] == \"action\" or r[\"_field\"] == \"direction\" or r[\"_field\"] == \"protocolid\" or r[\"_field\"] == \"host\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.host =~ /^.*$/ and r.action == \"block\" and r.direction == \"in\" and r.protocolid =~ /^(6$|17$)/)\n  |> group(columns:[\"src_ip\",\"dest_ip\",\"dest_port\"])\n  |> rename(columns:{action: \"Blocked\"})\n  |> count(column: \"Blocked\")\n  \n  |> group()  //use group to ungroup data and return to a single table\n  |> top(n:10, columns: [\"Blocked\"])  \n  |> sort(columns: [\"Blocked\"], desc: true)\n  |> yield()\n  ",
       "select": [
        [
         { "params": [ "action" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "action", "operator": "=", "value": "block" },
        { "condition": "AND", "key": "direction", "operator": "=", "value": "in" }
       ]
      }
     ]
    },
    {
     "title": "Port - Top 10 Blocked - IN",
     "type": "table",
     "gridPos": { "h": 9, "w": 3, "x": 6, "y": 15 },
     "targets": [
      {
       "alias": "$tag_src_ip",
       "groupBy": [
        { "params": [ "src_ip" ], "type": "tag" }
       ],
       "measurement": "tail_ipblock",
       "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\")\n\n  |> filter(fn: (r) => r[\"_field\"] == \"src_ip\" or r[\"_field\"] == \"dest_ip\" or r[\"_field\"] == \"dest_port\" or r[\"_field\"] == \"action\" or r[\"_field\"] == \"direction\" or r[\"_field\"] == \"protocolid\" or r[\"_field\"] == \"host\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.host =~ /^.*$/ and r.action == \"block\" and r.direction == \"in\" and r.protocolid =~ /^(6$|17$)/)\n  |> group(columns:[\"dest_port\"])\n  |> rename(columns:{action: \"Blocked\"})\n  |> count(column: \"Blocked\")\n  \n  |> group()  //use group to ungroup data and return to a single table\n  |> top(n:10, columns: [\"Blocked\"])  \n  |> sort(columns: [\"Blocked\"], desc: true)\n  |> yield()",
       "select": [
        [
         { "params": [ "action" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "action", "operator": "=", "value": "block" },
        { "condition": "AND", "key": "direction", "operator": "=", "value": "in" }
       ]
      }
     ]
    },
    {
     "title": "Top 10 DNSBL Feeds",
     "type": "table",
     "gridPos": { "h": 9, "w": 4, "x": 10, "y": 15 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "feed_name" ], "type": "tag" }
       ],
       "measurement": "tail_dnsbl_log",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_dnsbl_log\")\r\n  |> group(columns:[\"blocklist\",\"feed_name\"])\r\n  |> count(column: \"_value\")\r\n  |> rename(columns: { _value: \"Count\"})\r\n  |> group()  //use group to ungroup data and return to a single table\r\n  |> top(n:10, columns: [\"Count\"])  \r\n  |> sort(columns: [\"Count\"], desc: true)\r\n  |> yield()",
       "select": [
        [
         { "params": [ "blockmethod" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    },
    {
     "title": "Port - Top 10 Blocked - OUT",
     "type": "table",
     "gridPos": { "h": 9, "w": 3, "x": 16, "y": 15 },
     "targets": [
      {
       "alias": "$tag_src_ip",
       "groupBy": [
        { "params": [ "src_ip" ], "type": "tag" }
       ],
       "measurement": "tail_ipblock",
       "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\")\n\n  |> filter(fn: (r) => r[\"_field\"] == \"src_ip\" or r[\"_field\"] == \"dest_ip\" or r[\"_field\"] == \"dest_port\" or r[\"_field\"] == \"action\" or r[\"_field\"] == \"direction\" or r[\"_field\"] == \"protocolid\" or r[\"_field\"] == \"host\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.host =~ /^.*$/ and r.action == \"block\" and r.direction == \"out\" and r.protocolid =~ /^(6$|17$)/)\n  |> group(columns:[\"dest_port\"])\n  |> rename(columns:{action: \"Blocked\"})\n  |> count(column: \"Blocked\")\n  \n  |> group()  //use group to ungroup data and return to a single table\n  |> top(n:10, columns: [\"Blocked\"])  \n  |> sort(columns: [\"Blocked\"], desc: true)\n  |> yield()",
       "select": [
        [
         { "params": [ "action" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "action", "operator": "=", "value": "block" },
        { "condition": "AND", "key": "direction", "operator": "=", "value": "in" }
       ]
      }
     ]
    },
    {
     "title": "IP - Top 10 Blocked - OUT (By Host/Port)",
     "type": "table",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 15 },
     "targets": [
      {
       "alias": "$tag_src_ip",
       "groupBy": [
        { "params": [ "src_ip" ], "type": "tag" }
       ],
       "measurement": "tail_ipblock",
       "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\")\n\n  |> filter(fn: (r) => r[\"_field\"] == \"src_ip\" or r[\"_field\"] == \"dest_ip\" or r[\"_field\"] == \"dest_port\" or r[\"_field\"] == \"action\" or r[\"_field\"] == \"direction\" or r[\"_field\"] == \"protocolid\" or r[\"_field\"] == \"host\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.host =~ /^.*$/ and r.action == \"block\" and r.direction == \"out\" and r.protocolid =~ /^(6$|17$)/)\n  |> group(columns:[\"src_ip\",\"dest_ip\",\"dest_port\"])\n  |> rename(columns:{action: \"Blocked\"})\n  |> count(column: \"Blocked\")\n  \n  |> group()  //use group to ungroup data and return to a single table\n  |> top(n:10, columns: [\"Blocked\"])  \n  |> sort(columns: [\"Blocked\"], desc: true)\n  |> yield()\n  ",
       "select": [
        [
         { "params": [ "action" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "action", "operator": "=", "value": "block" },
        { "condition": "AND", "key": "direction", "operator": "=", "value": "in" }
       ]
      }
     ]
    },
    {
     "title": "IP - Top 10 Blocked - IN (By Host/Protocol)",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 24 },
     "targets": [
      {
       "alias": "$tag_src_ip",
       "groupBy": [
        { "params": [ "src_ip" ], "type": "tag" }
       ],
       "measurement": "tail_ipblock",
       "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\")\n\n  |> filter(fn: (r) => r[\"_field\"] == \"src_ip\" or r[\"_field\"] == \"dest_ip\" or r[\"_field\"] == \"dest_port\" or r[\"_field\"] == \"action\" or r[\"_field\"] == \"direction\" or r[\"_field\"] == \"protocolid\" or r[\"_field\"] == \"host\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.host =~ /^.*$/ and r.action == \"block\" and r.direction == \"in\" and r.protocolid =~ /^(6$|17$)/)\n  |> group(columns:[\"src_ip\",\"dest_ip\",\"protocol\"])\n  |> rename(columns:{action: \"Blocked\"})\n  |> count(column: \"Blocked\")\n  \n  |> group()  //use group to ungroup data and return to a single table\n  |> top(n:10, columns: [\"Blocked\"])  \n  |> sort(columns: [\"Blocked\"], desc: true)\n  |> yield()",
       "select": [
        [
         { "params": [ "action" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "action", "operator": "=", "value": "block" },
        { "condition": "AND", "key": "direction", "operator": "=", "value": "in" }
       ]
      }
     ]
    },
    {
     "title": "Protocol - Top 10 Blocked - IN",
     "type": "table",
     "gridPos": { "h": 9, "w": 3, "x": 6, "y": 24 },
     "targets": [
      {
       "alias": "$tag_protocol",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\")\n\n  |> filter(fn: (r) => r[\"_field\"] == \"src_ip\" or r[\"_field\"] == \"dest_ip\" or r[\"_field\"] == \"dest_port\" or r[\"_field\"] == \"action\" or r[\"_field\"] == \"direction\" or r[\"_field\"] == \"protocolid\" or r[\"_field\"] == \"host\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.host =~ /^.*$/ and r.action == \"block\" and r.direction == \"in\")\n  |> group(columns:[\"protocol\"])\n  |> rename(columns:{action: \"Blocked\"})\n  |> count(column: \"Blocked\")\n  \n  |> group()  //use group to ungroup data and return to a single table\n  |> top(n:10, columns: [\"Blocked\"])  \n  |> sort(columns: [\"Blocked\"], desc: true)\n  |> yield()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 10 IP Block Feeds",
     "type": "table",
     "gridPos": { "h": 9, "w": 4, "x": 10, "y": 24 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "feed_name" ], "type": "tag" }
       ],
       "measurement": "tail_dnsbl_log",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\")\r\n  |> group(columns:[\"feed_name\"])\r\n  |> count(column: \"_value\")\r\n  |> rename(columns: { _value: \"Count\"})\r\n  |> group()  //use group to ungroup data and return to a single table\r\n  |> top(n:10, columns: [\"Count\"])  \r\n  |> sort(columns: [\"Count\"], desc: true)\r\n  |> yield()",
       "select": [
        [
         { "params": [ "blockmethod" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    },
    {
     "title": "Protocol - Top 10 Blocked - OUT",
     "type": "table",
     "gridPos": { "h": 9, "w": 3, "x": 16, "y": 24 },
     "targets": [
      {
       "alias": "$tag_protocol",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\")\n\n  |> filter(fn: (r) => r[\"_field\"] == \"src_ip\" or r[\"_field\"] == \"dest_ip\" or r[\"_field\"] == \"dest_port\" or r[\"_field\"] == \"action\" or r[\"_field\"] == \"direction\" or r[\"_field\"] == \"protocolid\" or r[\"_field\"] == \"host\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.host =~ /^.*$/ and r.action == \"block\" and r.direction == \"out\" and r.protocolid =~ /^(6$|17$)/)\n  |> group(columns:[\"protocol\"])\n  |> rename(columns:{action: \"Blocked\"})\n  |> count(column: \"Blocked\")\n  \n  |> group()  //use group to ungroup data and return to a single table\n  |> top(n:10, columns: [\"Blocked\"])  \n  |> sort(columns: [\"Blocked\"], desc: true)\n  |> yield()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "IP - Top 10 Blocked - OUT (By Host/Protocol)",
     "type": "table",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 24 },
     "targets": [
      {
       "alias": "$tag_src_ip",
       "groupBy": [
        { "params": [ "src_ip" ], "type": "tag" }
       ],
       "measurement": "tail_ipblock",
       "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\")\n\n  |> filter(fn: (r) => r[\"_field\"] == \"src_ip\" or r[\"_field\"] == \"dest_ip\" or r[\"_field\"] == \"dest_port\" or r[\"_field\"] == \"action\" or r[\"_field\"] == \"direction\" or r[\"_field\"] == \"protocolid\" or r[\"_field\"] == \"host\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.host =~ /^.*$/ and r.action == \"block\" and r.direction == \"out\" and r.protocolid =~ /^(6$|17$)/)\n  |> group(columns:[\"src_ip\",\"dest_ip\",\"protocol\"])\n  |> rename(columns:{action: \"Blocked\"})\n  |> count(column: \"Blocked\")\n  \n  |> group()  //use group to ungroup data and return to a single table\n  |> top(n:10, columns: [\"Blocked\"])  \n  |> sort(columns: [\"Blocked\"], desc: true)\n  |> yield()",
       "select": [
        [
         { "params": [ "action" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "action", "operator": "=", "value": "block" },
        { "condition": "AND", "key": "direction", "operator": "=", "value": "in" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Unbound DNS Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Cache Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"unbound\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total_num_cachemiss\" or r[\"_field\"] == \"total_num_queries\" or r[\"_field\"] == \"total_num_cachehits\")\r\n  |> filter(fn: (r) => r[\"host\"] ==  \"${Host}\" )\r\n  |> keep(columns: [\"_time\",\"_field\",\"_value\"])    \r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Cache Query Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"unbound\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total_num_queries\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> derivative(unit: 1s, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\")\r\n  |> keep(columns: [\"_time\",\"_field\",\"_value\"])    \r\n  |> yield()"
    }
   ]
  },
  {
   "title": "DNS Cache Hit / Miss",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"unbound\")  \r\n  |> filter(fn: (r) => r[\"_field\"] == \"total_num_cachemiss\" or r[\"_field\"] == \"total_num_cachehits\")\r\n  |> filter(fn: (r) => r[\"host\"] ==  \"${Host}\" )\r\n  |> keep(columns: [\"_time\",\"_field\",\"_value\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Network Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gateway RTT - $Gateway ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_gateway_name",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "gateway_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gateways",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gateways\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"delay\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${Host:regex}$/)\r\n  |> filter(fn: (r) => r[\"gateway_name\"] =~ /^${Gateway:regex}$/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns:[\"_time\",\"gateway_name\",\"_value\"])",
       "select": [
        [
         { "params": [ "delay" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "gateway_name", "operator": "=~", "value": "/^$Gateway$/" }
       ]
      }
     ]
    },
    {
     "title": "Interface Summary",
     "type": "table",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 16 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "limit": "1",
       "measurement": "interface",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${Host:regex}$/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"name\"])\r\n  |> sort(columns: [\"_time\"])\r\n  |> last(column: \"_time\")\r\n  |> group()  //use group to ungroup data and return to a single table\r\n  //|> keep(columns:[\"name\",\"friendlyname\",\"ip4_address\",\"mac_address\",\"status\",\"ip6_address\"])\r\n  |> rename(columns: {\"name\":\"Interface\",friendlyname:\"FriendlyName\",\"ip4_address\":\"IPv4 Address\",\"mac_address\":\"Physical Address\",\r\n  \"status\":\"Status\",\"ip6_address\":\"IPv6 Address\"})",
       "select": [
        [
         { "params": [ "friendlyname" ], "type": "field" },
         { "params": [ "FriendlyName" ], "type": "alias" }
        ],
        [
         { "params": [ "ip4_address" ], "type": "field" },
         { "params": [ "IPv4 Address" ], "type": "alias" }
        ],
        [
         { "params": [ "mac_address" ], "type": "field" },
         { "params": [ "Physical Address" ], "type": "alias" }
        ],
        [
         { "params": [ "status" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Status" ], "type": "alias" }
        ],
        [
         { "params": [ "ip6_address" ], "type": "field" },
         { "params": [ "IPv6 Address" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    },
    {
     "title": "Gateway Loss - $Gateway ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_gateway_name",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "gateway_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gateways",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gateways\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"loss\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${Host:regex}$/)\r\n  |> filter(fn: (r) => r[\"gateway_name\"] =~ /^${Gateway:regex}$/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns:[\"_time\",\"gateway_name\",\"_value\"])",
       "select": [
        [
         { "params": [ "loss" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "gateway_name", "operator": "=~", "value": "/^$Gateway$/" }
       ]
      }
     ]
    },
    {
     "title": "Gateway Summary - $Gateway",
     "type": "table",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 24 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "gateway_name" ], "type": "tag" }
       ],
       "limit": "1",
       "measurement": "gateways",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gateways\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${Host:regex}$/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"gateway_name\"])\r\n  |> sort(columns: [\"_time\"])\r\n  |> last(column: \"_time\")\r\n  |> group()  //use group to ungroup data and return to a single table\r\n  ",
       "select": [
        [
         { "params": [ "gwdescr" ], "type": "field" }
        ],
        [
         { "params": [ "source" ], "type": "field" }
        ],
        [
         { "params": [ "monitor" ], "type": "field" }
        ],
        [
         { "params": [ "defaultgw" ], "type": "field" }
        ],
        [
         { "params": [ "status" ], "type": "field" }
        ],
        [
         { "params": [ "substatus" ], "type": "field" }
        ],
        [
         { "params": [ "interface" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "WAN Interface - $WAN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "repeat": "WAN",
   "collapsed": true,
   "panels": [
    {
     "title": "Interface summary",
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "limit": "1",
       "measurement": "interface",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${Host:regex}$/)\r\n  |> filter(fn: (r) => r[\"name\"] =~ /^${WAN:regex}$/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"name\"])\r\n  |> last(column: \"_time\")\r\n  |> group()  //use group to ungroup data and return to a single table\r\n  //|> keep(columns:[\"name\",\"friendlyname\",\"ip4_address\",\"mac_address\",\"status\",\"ip6_address\"])\r\n  |> rename(columns: {\"name\":\"Interface\",friendlyname:\"FriendlyName\",\"ip4_address\":\"IPv4 Address\",\"mac_address\":\"Physical Address\",\r\n  \"status\":\"Status\",\"ip6_address\":\"IPv6 Address\"})",
       "select": [
        [
         { "params": [ "friendlyname" ], "type": "field" },
         { "params": [ "FriendlyName" ], "type": "alias" }
        ],
        [
         { "params": [ "ip4_address" ], "type": "field" },
         { "params": [ "IPv4 Address" ], "type": "alias" }
        ],
        [
         { "params": [ "mac_address" ], "type": "field" },
         { "params": [ "Physical Address" ], "type": "alias" }
        ],
        [
         { "params": [ "status" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Status" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$WAN$/" }
       ]
      }
     ]
    },
    {
     "title": "WAN Traffic - $WAN (Bytes/sec)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_interface - $col",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${Host:regex}$/)\r\n  |> filter(fn: (r) => r[\"interface\"] =~ /^${WAN:regex}$/)\r\n  |> filter(fn: (r)=> r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"interface\"])\r\n  |> derivative(columns: [\"bytes_recv\",\"bytes_sent\"], nonNegative: true, timeColumn: \"_time\", unit: 1s)\r\n  \r\n  |> keep(columns:[\"_time\",\"bytes_recv\",\"bytes_sent\"])",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "first"
         },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           "* count(\"bytes_recv\") / count(\"bytes_recv\")"
          ],
          "type": "math"
         },
         { "params": [ "Bytes_Recv" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "first"
         },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           "* count(\"bytes_sent\") / count(\"bytes_sent\")"
          ],
          "type": "math"
         },
         { "params": [ "Bytes_Sent" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$WAN$/" }
       ]
      }
     ]
    },
    {
     "title": "WAN Traffic - $WAN (Bytes/sec)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 9, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$tag_interface - $col",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${Host:regex}$/)\r\n  |> filter(fn: (r) => r[\"interface\"] =~ /^${WAN:regex}$/)\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"interface\"])\r\n  |> derivative(columns: [\"bytes_recv\",\"bytes_sent\"], nonNegative: true, timeColumn: \"_time\", unit: 1s)\r\n  |> keep(columns:[\"_time\",\"interface\",\"bytes_recv\",\"bytes_sent\"])",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "first"
         },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           "* count(\"bytes_recv\") / count(\"bytes_recv\") * 8"
          ],
          "type": "math"
         },
         { "params": [ "Bits_Recv" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "first"
         },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           "* count(\"bytes_sent\") / count(\"bytes_sent\") * 8"
          ],
          "type": "math"
         },
         { "params": [ "Bits_Sent" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$WAN$/" }
       ]
      }
     ]
    },
    {
     "title": "WAN $WAN",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "alias": "$tag_interface - $col - This Month",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${Host:regex}$/)\r\n  |> filter(fn: (r) => r[\"interface\"] =~ /^${WAN:regex}$/)\r\n  |> filter(fn: (r)=> r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> difference(columns: [\"bytes_recv\",\"bytes_sent\"], nonNegative:true,keepFirst:false)\r\n  |> keep(columns:[\"_time\",\"interface\",\"bytes_recv\",\"bytes_sent\"])",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "first"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "Bytes_Recv" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "first"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "Bytes_Sent" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$WAN$/" }
       ]
      }
     ]
    },
    {
     "title": "WAN Throughput - $WAN",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_interface - $col",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${Host:regex}$/)\r\n  |> filter(fn: (r) => r[\"interface\"] =~ /^${WAN:regex}$/)\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"interface\"])\r\n  |> derivative(columns: [\"packets_recv\",\"packets_sent\"], nonNegative: true, timeColumn: \"_time\", unit: 1s)\r\n  |> keep(columns:[\"_time\",\"interface\",\"packets_recv\",\"packets_sent\"])",
       "select": [
        [
         { "params": [ "packets_recv" ], "type": "field" },
         {
          "params": [],
          "type": "first"
         },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           "* count(\"packets_recv\") / count(\"packets_recv\")"
          ],
          "type": "math"
         },
         { "params": [ "Packets_Recv" ], "type": "alias" }
        ],
        [
         { "params": [ "packets_sent" ], "type": "field" },
         {
          "params": [],
          "type": "first"
         },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           "* count(\"packets_sent\") / count(\"packets_sent\")"
          ],
          "type": "math"
         },
         { "params": [ "Packets_Sent" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      },
      {
       "alias": "$tag_interface - $col",
       "groupBy": [
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${Host:regex}$/)\r\n  |> filter(fn: (r) => r[\"interface\"] =~ /^${WAN:regex}$/)\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"interface\"])\r\n  |> keep(columns:[\"_time\",\"interface\",\"drop_in\",\"drop_out\",\"err_in\",\"err_out\"])",
       "select": [
        [
         { "params": [ "drop_in" ], "type": "field" },
         { "params": [ "Drop_In" ], "type": "alias" }
        ],
        [
         { "params": [ "drop_out" ], "type": "field" },
         { "params": [ "Drop_Out" ], "type": "alias" }
        ],
        [
         { "params": [ "err_in" ], "type": "field" },
         { "params": [ "Err_In" ], "type": "alias" }
        ],
        [
         { "params": [ "err_out" ], "type": "field" },
         { "params": [ "Err_Out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "LAN Interface - $LAN_Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "repeat": "LAN_Interfaces",
   "collapsed": true,
   "panels": [
    {
     "title": "Interface summary",
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "limit": "1",
       "measurement": "interface",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${Host:regex}$/)\r\n  |> filter(fn: (r) => r[\"name\"] =~ /^${LAN_Interfaces:regex}$/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"name\"])\r\n  |> last(column: \"_time\")\r\n  |> group()  //use group to ungroup data and return to a single table\r\n  //|> keep(columns:[\"name\",\"friendlyname\",\"ip4_address\",\"mac_address\",\"status\",\"ip6_address\"])\r\n  |> rename(columns: {\"name\":\"Interface\",friendlyname:\"FriendlyName\",\"ip4_address\":\"IPv4 Address\",\"mac_address\":\"Physical Address\",\r\n  \"status\":\"Status\",\"ip6_address\":\"IPv6 Address\"})",
       "select": [
        [
         { "params": [ "friendlyname" ], "type": "field" },
         { "params": [ "FriendlyName" ], "type": "alias" }
        ],
        [
         { "params": [ "ip4_address" ], "type": "field" },
         { "params": [ "IPv4 Address" ], "type": "alias" }
        ],
        [
         { "params": [ "mac_address" ], "type": "field" },
         { "params": [ "Physical Address" ], "type": "alias" }
        ],
        [
         { "params": [ "status" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Status" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
       ]
      }
     ]
    },
    {
     "title": "LAN Traffic - $LAN_Interfaces (Bytes/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_interface - $col",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${Host:regex}$/)\r\n  |> filter(fn: (r) => r[\"interface\"] =~ /^${LAN_Interfaces:regex}$/)\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"interface\"])\r\n  |> derivative(columns: [\"bytes_recv\",\"bytes_sent\"], nonNegative: true, timeColumn: \"_time\", unit: 1s)\r\n  |> keep(columns:[\"_time\",\"bytes_recv\",\"bytes_sent\"])",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "first"
         },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           "* count(\"bytes_recv\") / count(\"bytes_recv\")"
          ],
          "type": "math"
         },
         { "params": [ "Bytes_Recv" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "first"
         },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           "* count(\"bytes_sent\") / count(\"bytes_sent\")"
          ],
          "type": "math"
         },
         { "params": [ "Bytes_Sent" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
       ]
      }
     ]
    },
    {
     "title": "LAN Traffic - $LAN_Interfaces (Bytes/sec)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 9, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$tag_interface - $col",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${Host:regex}$/)\r\n  |> filter(fn: (r) => r[\"interface\"] =~ /^${LAN_Interfaces:regex}$/)\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"interface\"])\r\n  |> derivative(columns: [\"bytes_recv\",\"bytes_sent\"], nonNegative: true, timeColumn: \"_time\", unit: 1s)\r\n  |> keep(columns:[\"_time\",\"interface\",\"bytes_recv\",\"bytes_sent\"])",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "first"
         },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           "* count(\"bytes_recv\") / count(\"bytes_recv\") * 8"
          ],
          "type": "math"
         },
         { "params": [ "Bits_Recv" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "first"
         },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           "* count(\"bytes_sent\") / count(\"bytes_sent\") * 8"
          ],
          "type": "math"
         },
         { "params": [ "Bits_Sent" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
       ]
      }
     ]
    },
    {
     "title": "LAN $LAN_Interfaces",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "alias": "$tag_interface - $col - This Month",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${Host:regex}$/)\r\n  |> filter(fn: (r) => r[\"interface\"] =~ /^${LAN_Interfaces:regex}$/)\r\n  |> filter(fn: (r)=> r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> difference(columns: [\"bytes_recv\",\"bytes_sent\"], nonNegative:true,keepFirst:false)\r\n  |> keep(columns:[\"_time\",\"interface\",\"bytes_recv\",\"bytes_sent\"])",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "first"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "Bytes_Recv" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "first"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "Bytes_Sent" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
       ]
      }
     ]
    },
    {
     "title": "LAN Throughput - $LAN_Interfaces",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_interface - $col",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${Host:regex}$/)\r\n  |> filter(fn: (r) => r[\"interface\"] =~ /^${LAN_Interfaces:regex}$/)\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"interface\"])\r\n  |> derivative(columns: [\"packets_recv\",\"packets_sent\"], nonNegative: true, timeColumn: \"_time\", unit: 1s)\r\n  |> keep(columns:[\"_time\",\"interface\",\"packets_recv\",\"packets_sent\"])",
       "select": [
        [
         { "params": [ "packets_recv" ], "type": "field" },
         {
          "params": [],
          "type": "first"
         },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           "* count(\"packets_recv\") / count(\"packets_recv\")"
          ],
          "type": "math"
         },
         { "params": [ "Packets_Recv" ], "type": "alias" }
        ],
        [
         { "params": [ "packets_sent" ], "type": "field" },
         {
          "params": [],
          "type": "first"
         },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           "* count(\"packets_sent\") / count(\"packets_sent\")"
          ],
          "type": "math"
         },
         { "params": [ "Packets_Sent" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      },
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${Host:regex}$/)\r\n  |> filter(fn: (r) => r[\"interface\"] =~ /^${LAN_Interfaces:regex}$/)\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"interface\"])\r\n  |> keep(columns:[\"_time\",\"interface\",\"drop_in\",\"drop_out\",\"err_in\",\"err_out\"])"
      }
     ]
    }
   ]
  }
 ]
}